### ISSUE TITLE
Manifest File Extra Features

### ISSUE THREAD

**Issue by mskian** [zerosonesfun/pwa#1]
Thanks a lot for this Awesome Extension

- [x] Title
- [x] Description
- [x] Shortname
- [x] ICONS (Add Extra Icons 44, 72, 96, and 144)
- [x]  Theme Color
- [x] Background Color
- [x] orientation - https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation
- [x] Start (add start URL with URL Parametrs Help us to track the PWA install & events
- [x] Display
- [x] Scope
- [ ] Apple Device touch Meta Headers
- [ ] Ignore Flarum admin page caching
- [ ] **Optional Feature** - Dynamically add the forum meta theme color in Manifest also description

- Dynamically adjust the Manifest file example match the forum theme color on Manifest also description
- Ignore Flarum admin page from PWA caching
- Add APPLE `apple-touch-icon` Headers (Recommended by Google Chrome Lighthouse Audit)

```
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="white-translucent">
<meta name="apple-mobile-web-app-title" content="Forum">

<link rel="apple-touch-icon" href="icons/Icon-48.png">
<link rel="apple-touch-icon" sizes="72x72" href="icons/Icon-72.png">
<link rel="apple-touch-icon" sizes="96x96" href="icons/Icon-96.png">
<link rel="apple-touch-icon" sizes="144x144" href="icons/Icon-144.png">
<link rel="apple-touch-icon" sizes="192x192" href="icons/Icon-192.png">
<link rel="apple-touch-icon" sizes="256x256" href="icons/Icon-256.png">
<link rel="apple-touch-icon" sizes="512x512" href="icons/Icon-512.png">
```

**Comment by zerosonesfun** [comment]
Hi @mskian, 

Thank you for taking the time to provide these suggestions. First, let me explain why this extension does not include all of the other icons. When I made this extension I already had all of the apple touch icons included in my site's head. And I got to thinking, what if other people already have these icons added to their site too? I didn't want there to be duplicate icons and conflicts. Therefore, I only added the two PWA specific icons. Any Apple icons, Android icons, Windows icons, etc., need to be added separately by the webmaster. This ensures there are no conflicts, and it allows the webmaster to include whatever icons they would like and store them in any folder they would like. Just in case you are not aware, [here's how to add these icons to Flarum's head](https://discuss.flarum.org/d/20162-how-to-add-to-head-head).

As far as making the extension more dynamic and possibly even adding settings in the admin, I can't make any promises, I may never get around to doing this. But, feel free to fork this and/or do a pull request if you know how to add these features.

Ignoring caching in admin is done because all caching has been removed in the latest version. The caching was causing logging in and out issues on certain devices/browsers.
